name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev cmake
      
    - name: Compile Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Build
      run: cd app && make -j$(nproc)
      
    - name: Run Tests
      run: cd app && make test
