name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev cmake
    - name: Configure (if needed)
      run: ./configure || true  # Skip if not applicable
    - name: Build
      run: make -C app -j$(nproc)
    - name: Run Tests
      run: make -C app test
